version: "3.9"
services:
  backend:
    build: ./backend
    container_name: node-backend
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend
    container_name: node-frontend
    ports:
      - "80:80"
    depends_on:
      - backend